def set_plugin_data(data: dict):
    ...
def raise_event(values: dict):
    ...
def log_debug(msg, *args, **kwargs):
    ...
def capture_regions(regions: list[str] = [], debug=False) -> bool:
    ...
def match_template(template: str, region: str, filter=None, debug: bool = False) -> None | dict:
    ...
def get_region_fill_ratio(region: str, filter, debug: bool = False) -> float:
    ...
def cv_in_range(img, lower: 'tuple', upper: 'tuple'):
    ...
